name: Build and Test

on:
  push:
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  PR_AUTHOR: ${{ github.event.pull_request.user.login }}
  PR_NUM: ${{ github.event.pull_request.number }}
  PR_AUTHOR_FULL_NAME: ${{ github.event.pull_request.user.name }}
  PR_AUTHOR_EMAIL: ${{ github.event.pull_request.user.email }}
  PR_AUTHOR_FORK: ${{ github.event.pull_request.head.repo.full_name }}
  SOURCE_BRANCH_NAME: ${{ github.head_ref }}
  TARGET_BRANCH_NAME: ${{ github.base_ref }}

jobs:
  Ubuntu-20-04-x86_64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: PR info
      run: |
          echo "PR Num: ${{ env.PR_NUM }}"
          echo "PR Author: ${{ env.PR_AUTHOR }}"
          echo "PR Author Full Name: ${{ env.PR_AUTHOR_FULL_NAME }}"
          echo "PR Author email: ${{ env.PR_AUTHOR_EMAIL }}"
          echo "PR Author fork: ${{ env.PR_AUTHOR_FORK }}"
          echo "Source branch name: ${{ env.SOURCE_BRANCH_NAME }}"
          echo "Target branch name: ${{ env.TARGET_BRANCH_NAME }}"
    - name: Install dependency packages
      run: |
          sudo apt install -y --no-install-recommends \
            git \
            cmake \
            clang-format
    - name: Merge fork with upstream locally
      run: |
          git config pull.rebase true
          # git clone --branch ${{ env.TARGET_BRANCH_NAME }} https://github.com/KoopaEngine/arrow.git
          git pull -v "https://github.com/${{ env.PR_AUTHOR_FORK }}" "${{ env.SOURCE_BRANCH_NAME }}"
          git status
    - name: Format code
      run: | 
          find . -regex '.*\.\(cpp\|hpp\|cxx\|cp\|cc\|cu\|c\|h\)' -not -path '*/extern/*' -exec clang-format -style=file -i {} \;
          git diff
    - name: Commit formated code
      run: |
          git config user.name "Github Action Bot" 
          git config user.email "actions@users.noreply.github.com"
          git add .
          git status
          git remote -v
          # git fetch upstream pull/{{env.PR_NUM}}/head:pr{{env.PR_NUM}}
          # git checkout pr{{env.PR_NUM}}
          git commit -m "Format code"
    - name: Push formatted code
      run: |
          # git push  "https://github.com/${{ env.PR_AUTHOR_FORK }}" "main:${{ env.SOURCE_BRANCH_NAME }}"
          git push origin pull/${{env.PR_NUM}}/merge
          # git push upstream pull/{{env.PR_NUM}}/head:pr{{env.PR_NUM}}
#     - name : Format
#       run: find . -regex '.*\.\(cpp\|hpp\|cxx\|cp\|cc\|cu\|c\|h\)' -exec clang-format -style=file -i {} \;
    - name : Configure
      run: cmake -DBUILD_TESTING=ON -S . -B build
    - name : Build
      run: cmake --build build -j$(nproc --all)
    - name : Run Tests
      run: |
          cd build
          ctest
